// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejhfqkltaailtvawykow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqaGZxa2x0YWFpbHR2YXd5a293Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MDA2OTEsImV4cCI6MjA3MzA3NjY5MX0.DYPmURbDo29IE_PftFMdJzHHFaSM_8p8eYDPhFA6UQ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});